name: news_app_clean_architecture
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #icon
  ionicons: ^0.2.2

  #state management
  flutter_bloc: ^9.1.1

  #comparing dart objects
  equatable: ^2.0.5

  #service locator
  get_it: ^9.2.1
  
  #dateFormat
  intl: ^0.20.2

  #Database
  floor: ^1.4.0

  #make request to api
  retrofit: ^4.9.2

  # Firebase
  firebase_core: ^4.6.0
  firebase_auth: ^6.3.0
  cloud_firestore: ^6.2.0
  firebase_storage: ^13.2.0

  # Media
  image_picker: ^1.0.7

  # Auth
  google_sign_in: ^7.2.0


  #Hooks
  flutter_hooks: ^0.21.3+1

  #chached image 
  cached_network_image: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  retrofit_generator: ^9.2.0
  floor_generator: ^1.5.0
  build_runner: ^2.4.8
  mockito: ^5.4.4
  bloc_test: ^10.0.0
  

flutter:

  uses-material-design: true

 
  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli.ttf
        - asset: assets/fonts/muli/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/muli/Muli-Light.ttf
          weight: 300
